#! /usr/bin/env python

"""
:Author: David Goodger
:Contact: goodger@users.sourceforge.net
:Revision: $Revision: 1.11 $
:Date: $Date: 2002/03/16 05:47:58 $
:Copyright: This module has been placed in the public domain.

Tests for dps.transforms.references.Footnotes.
"""

import DPSTestSupport
from dps.transforms.references import Footnotes
import UnitTestFolder
try:
    from restructuredtext import Parser
except ImportError:
    from dps.parsers.restructuredtext import Parser


def suite():
    parser = Parser()
    s = DPSTestSupport.TransformTestSuite(parser)
    s.generateTests(totest)
    return s

totest = {}

totest['footnotes'] = ((Footnotes,), [
["""\
[#autolabel]_

.. [#autolabel] text
""",
"""\
<document>
    <paragraph>
        <footnote_reference auto="1" refname="autolabel">
            1
    <footnote auto="1" id="autolabel" name="autolabel">
        <label>
            1
        <paragraph>
            text
"""],
["""\
autonumber: [#]_

.. [#] text
""",
"""\
<document>
    <paragraph>
        autonumber: \n\
        <footnote_reference auto="1" refname="1">
            1
    <footnote auto="1" id="id1" name="1">
        <label>
            1
        <paragraph>
            text
"""],
["""\
[#]_ is the first auto-numbered footnote reference.
[#]_ is the second auto-numbered footnote reference.

.. [#] Auto-numbered footnote 1.
.. [#] Auto-numbered footnote 2.
.. [#] Auto-numbered footnote 3.

[#]_ is the third auto-numbered footnote reference.
""",
"""\
<document>
    <paragraph>
        <footnote_reference auto="1" refname="1">
            1
         is the first auto-numbered footnote reference.
        <footnote_reference auto="1" refname="2">
            2
         is the second auto-numbered footnote reference.
    <footnote auto="1" id="id1" name="1">
        <label>
            1
        <paragraph>
            Auto-numbered footnote 1.
    <footnote auto="1" id="id2" name="2">
        <label>
            2
        <paragraph>
            Auto-numbered footnote 2.
    <footnote auto="1" id="id3" name="3">
        <label>
            3
        <paragraph>
            Auto-numbered footnote 3.
    <paragraph>
        <footnote_reference auto="1" refname="3">
            3
         is the third auto-numbered footnote reference.
"""],
["""\
[#third]_ is a reference to the third auto-numbered footnote.

.. [#first] First auto-numbered footnote.
.. [#second] Second auto-numbered footnote.
.. [#third] Third auto-numbered footnote.

[#second]_ is a reference to the second auto-numbered footnote.
[#first]_ is a reference to the first auto-numbered footnote.
[#third]_ is another reference to the third auto-numbered footnote.

Here are some internal cross-references to the implicit targets
generated by the footnotes: first_, second_, third_.
""",
"""\
<document>
    <paragraph>
        <footnote_reference auto="1" refname="third">
            3
         is a reference to the third auto-numbered footnote.
    <footnote auto="1" id="first" name="first">
        <label>
            1
        <paragraph>
            First auto-numbered footnote.
    <footnote auto="1" id="second" name="second">
        <label>
            2
        <paragraph>
            Second auto-numbered footnote.
    <footnote auto="1" id="third" name="third">
        <label>
            3
        <paragraph>
            Third auto-numbered footnote.
    <paragraph>
        <footnote_reference auto="1" refname="second">
            2
         is a reference to the second auto-numbered footnote.
        <footnote_reference auto="1" refname="first">
            1
         is a reference to the first auto-numbered footnote.
        <footnote_reference auto="1" refname="third">
            3
         is another reference to the third auto-numbered footnote.
    <paragraph>
        Here are some internal cross-references to the implicit targets
        generated by the footnotes: \n\
        <reference refname="first">
            first
        , \n\
        <reference refname="second">
            second
        , \n\
        <reference refname="third">
            third
        .
"""],
["""\
Mixed anonymous and labelled auto-numbered footnotes:

[#four]_ should be 4, [#]_ should be 1,
[#]_ should be 3, [#]_ is one too many,
[#two]_ should be 2, and [#six]_ doesn't exist.

.. [#] Auto-numbered footnote 1.
.. [#two] Auto-numbered footnote 2.
.. [#] Auto-numbered footnote 3.
.. [#four] Auto-numbered footnote 4.
.. [#five] Auto-numbered footnote 5.
.. [#five] Auto-numbered footnote 5 again (duplicate).
""",
"""\
<document>
    <paragraph>
        Mixed anonymous and labelled auto-numbered footnotes:
    <paragraph>
        <footnote_reference auto="1" refname="four">
            4
         should be 4, \n\
        <footnote_reference auto="1" refname="1">
            1
         should be 1,
        <footnote_reference auto="1" refname="3">
            3
         should be 3, \n\
        <problematic refid="id4">
            [#]_
         is one too many,
        <footnote_reference auto="1" refname="two">
            2
         should be 2, and \n\
        <footnote_reference auto="1" refname="six">
         doesn't exist.
    <footnote auto="1" id="id2" name="1">
        <label>
            1
        <paragraph>
            Auto-numbered footnote 1.
    <footnote auto="1" id="two" name="two">
        <label>
            2
        <paragraph>
            Auto-numbered footnote 2.
    <footnote auto="1" id="id3" name="3">
        <label>
            3
        <paragraph>
            Auto-numbered footnote 3.
    <footnote auto="1" id="four" name="four">
        <label>
            4
        <paragraph>
            Auto-numbered footnote 4.
    <footnote auto="1" dupname="five" id="five">
        <label>
            5
        <paragraph>
            Auto-numbered footnote 5.
    <footnote auto="1" dupname="five" id="id1">
        <label>
            6
        <system_message level="2" refid="id1" type="WARNING">
            <paragraph>
                Duplicate explicit target name: "five"
        <paragraph>
            Auto-numbered footnote 5 again (duplicate).
    <system_message id="id4" level="3" type="ERROR">
        <paragraph>
            Too many autonumbered footnote references: only 2 corresponding footnotes available.
"""],
["""\
Mixed auto-numbered and manual footnotes:

.. [1] manually numbered
.. [#] auto-numbered
.. [#label] autonumber-labeled
""",
"""\
<document>
    <paragraph>
        Mixed auto-numbered and manual footnotes:
    <footnote id="id1" name="1">
        <label>
            1
        <paragraph>
            manually numbered
    <footnote auto="1" id="id2" name="2">
        <label>
            2
        <paragraph>
            auto-numbered
    <footnote auto="1" id="label" name="label">
        <label>
            3
        <paragraph>
            autonumber-labeled
"""],
["""\
A labeled autonumbered footnote referece: [#footnote]_.

An unlabeled autonumbered footnote referece: [#]_.

.. [#] Unlabeled autonumbered footnote.
.. [#footnote] Labeled autonumbered footnote.
   Note that the footnotes are not in the same
   order as the references.
""",
"""\
<document>
    <paragraph>
        A labeled autonumbered footnote referece: \n\
        <footnote_reference auto="1" refname="footnote">
            2
        .
    <paragraph>
        An unlabeled autonumbered footnote referece: \n\
        <footnote_reference auto="1" refname="1">
            1
        .
    <footnote auto="1" id="id1" name="1">
        <label>
            1
        <paragraph>
            Unlabeled autonumbered footnote.
    <footnote auto="1" id="footnote" name="footnote">
        <label>
            2
        <paragraph>
            Labeled autonumbered footnote.
            Note that the footnotes are not in the same
            order as the references.
"""],
["""\
Mixed manually-numbered, anonymous auto-numbered,
and labelled auto-numbered footnotes:

[#four]_ should be 4, [#]_ should be 2,
[1]_ is 1, [3]_ is 3,
[#]_ should be 6, [#]_ is one too many,
[#five]_ should be 5, and [#eight]_ doesn't exist.

.. [1] Manually-numbered footnote 1.
.. [#] Auto-numbered footnote 2.
.. [#four] Auto-numbered footnote 4.
.. [3] Manually-numbered footnote 3
.. [#five] Auto-numbered footnote 5.
.. [#] Auto-numbered footnote 6.
.. [#five] Auto-numbered footnote 5 again (duplicate).
""",
"""\
<document>
    <paragraph>
        Mixed manually-numbered, anonymous auto-numbered,
        and labelled auto-numbered footnotes:
    <paragraph>
        <footnote_reference auto="1" refname="four">
            4
         should be 4, \n\
        <footnote_reference auto="1" refname="2">
            2
         should be 2,
        <footnote_reference refname="1">
            1
         is 1, \n\
        <footnote_reference refname="3">
            3
         is 3,
        <footnote_reference auto="1" refname="6">
            6
         should be 6, \n\
        <problematic refid="id6">
            [#]_
         is one too many,
        <footnote_reference auto="1" refname="five">
         should be 5, and \n\
        <footnote_reference auto="1" refname="eight">
         doesn't exist.
    <footnote id="id1" name="1">
        <label>
            1
        <paragraph>
            Manually-numbered footnote 1.
    <footnote auto="1" id="id4" name="2">
        <label>
            2
        <paragraph>
            Auto-numbered footnote 2.
    <footnote auto="1" id="four" name="four">
        <label>
            4
        <paragraph>
            Auto-numbered footnote 4.
    <footnote id="id2" name="3">
        <label>
            3
        <paragraph>
            Manually-numbered footnote 3
    <footnote auto="1" dupname="five" id="five">
        <label>
            5
        <paragraph>
            Auto-numbered footnote 5.
    <footnote auto="1" id="id5" name="6">
        <label>
            6
        <paragraph>
            Auto-numbered footnote 6.
    <footnote auto="1" dupname="five" id="id3">
        <label>
            7
        <system_message level="2" refid="id3" type="WARNING">
            <paragraph>
                Duplicate explicit target name: "five"
        <paragraph>
            Auto-numbered footnote 5 again (duplicate).
    <system_message id="id6" level="3" type="ERROR">
        <paragraph>
            Too many autonumbered footnote references: only 2 corresponding footnotes available.
"""],
["""\
Referencing a footnote by symbol [*]_.

.. [*] This is an auto-symbol footnote.
""",
"""\
<document>
    <paragraph>
        Referencing a footnote by symbol \n\
        <footnote_reference auto="*" refid="id1">
            *
        .
    <footnote auto="*" id="id1">
        <label>
            *
        <paragraph>
            This is an auto-symbol footnote.
"""],
["""\
A sequence of symbol footnote references:
[*]_ [*]_ [*]_ [*]_ [*]_ [*]_ [*]_ [*]_ [*]_ [*]_ [*]_ [*]_.

.. [*] Auto-symbol footnote 1.
.. [*] Auto-symbol footnote 2.
.. [*] Auto-symbol footnote 3.
.. [*] Auto-symbol footnote 4.
.. [*] Auto-symbol footnote 5.
.. [*] Auto-symbol footnote 6.
.. [*] Auto-symbol footnote 7.
.. [*] Auto-symbol footnote 8.
.. [*] Auto-symbol footnote 9.
.. [*] Auto-symbol footnote 10.
.. [*] Auto-symbol footnote 11.
.. [*] Auto-symbol footnote 12.
""",
u"""\
<document>
    <paragraph>
        A sequence of symbol footnote references:
        <footnote_reference auto="*" refid="id1">
            *
         \n\
        <footnote_reference auto="*" refid="id2">
            \u2020
         \n\
        <footnote_reference auto="*" refid="id3">
            \u2021
         \n\
        <footnote_reference auto="*" refid="id4">
            \u00A7
         \n\
        <footnote_reference auto="*" refid="id5">
            \u00B6
         \n\
        <footnote_reference auto="*" refid="id6">
            #
         \n\
        <footnote_reference auto="*" refid="id7">
            \u2660
         \n\
        <footnote_reference auto="*" refid="id8">
            \u2665
         \n\
        <footnote_reference auto="*" refid="id9">
            \u2666
         \n\
        <footnote_reference auto="*" refid="id10">
            \u2663
         \n\
        <footnote_reference auto="*" refid="id11">
            **
         \n\
        <footnote_reference auto="*" refid="id12">
            \u2020\u2020
        .
    <footnote auto="*" id="id1">
        <label>
            *
        <paragraph>
            Auto-symbol footnote 1.
    <footnote auto="*" id="id2">
        <label>
            \u2020
        <paragraph>
            Auto-symbol footnote 2.
    <footnote auto="*" id="id3">
        <label>
            \u2021
        <paragraph>
            Auto-symbol footnote 3.
    <footnote auto="*" id="id4">
        <label>
            \u00A7
        <paragraph>
            Auto-symbol footnote 4.
    <footnote auto="*" id="id5">
        <label>
            \u00B6
        <paragraph>
            Auto-symbol footnote 5.
    <footnote auto="*" id="id6">
        <label>
            #
        <paragraph>
            Auto-symbol footnote 6.
    <footnote auto="*" id="id7">
        <label>
            \u2660
        <paragraph>
            Auto-symbol footnote 7.
    <footnote auto="*" id="id8">
        <label>
            \u2665
        <paragraph>
            Auto-symbol footnote 8.
    <footnote auto="*" id="id9">
        <label>
            \u2666
        <paragraph>
            Auto-symbol footnote 9.
    <footnote auto="*" id="id10">
        <label>
            \u2663
        <paragraph>
            Auto-symbol footnote 10.
    <footnote auto="*" id="id11">
        <label>
            **
        <paragraph>
            Auto-symbol footnote 11.
    <footnote auto="*" id="id12">
        <label>
            \u2020\u2020
        <paragraph>
            Auto-symbol footnote 12.
"""],
])


if __name__ == '__main__':
    import unittest
    unittest.main(defaultTest='suite')
