#! /usr/bin/env python

"""
:Author: David Goodger
:Contact: goodger@users.sourceforge.net
:Revision: $Revision: 1.12 $
:Date: $Date: 2002/02/20 04:25:02 $
:Copyright: This module has been placed in the public domain.

Tests for states.py.
"""

import RSTTestSupport

def suite():
    s = RSTTestSupport.ParserTestSuite()
    s.generateTests(totest)
    return s

totest = {}

totest['footnotes'] = [
["""\
.. [footnote] This is a footnote.
""",
"""\
<document>
    <footnote id="id1" name="footnote">
        <label>
            footnote
        <paragraph>
            This is a footnote.
"""],
["""\
.. [footnote] This is a footnote
   on multiple lines.
""",
"""\
<document>
    <footnote id="id1" name="footnote">
        <label>
            footnote
        <paragraph>
            This is a footnote
            on multiple lines.
"""],
["""\
.. [footnote1] This is a footnote
     on multiple lines with more space.

.. [footnote2] This is a footnote
  on multiple lines with less space.
""",
"""\
<document>
    <footnote id="id1" name="footnote1">
        <label>
            footnote1
        <paragraph>
            This is a footnote
            on multiple lines with more space.
    <footnote id="id2" name="footnote2">
        <label>
            footnote2
        <paragraph>
            This is a footnote
            on multiple lines with less space.
"""],
["""\
.. [footnote]
   This is a footnote on multiple lines
   whose block starts on line 2.
""",
"""\
<document>
    <footnote id="id1" name="footnote">
        <label>
            footnote
        <paragraph>
            This is a footnote on multiple lines
            whose block starts on line 2.
"""],
["""\
.. [footnote]

That was an empty footnote.
""",
"""\
<document>
    <footnote id="id1" name="footnote">
        <label>
            footnote
    <paragraph>
        That was an empty footnote.
"""],
["""\
.. [footnote]
No blank line.
""",
"""\
<document>
    <footnote id="id1" name="footnote">
        <label>
            footnote
    <system_message level="2" type="WARNING">
        <paragraph>
            Unindent without blank line at line 2.
    <paragraph>
        No blank line.
"""],
["""\
.. [foot label with spaces] this isn't a footnote

.. [*footlabelwithmarkup*] this isn't a footnote
""",
"""\
<document>
    <comment>
        [foot label with spaces] this isn't a footnote
    <comment>
        [*footlabelwithmarkup*] this isn't a footnote
"""],
]

totest['auto_numbered_footnotes'] = [
["""\
[#]_ is the first auto-numbered footnote reference.
[#]_ is the second auto-numbered footnote reference.

.. [#] Auto-numbered footnote 1.
.. [#] Auto-numbered footnote 2.
.. [#] Auto-numbered footnote 3.

[#]_ is the third auto-numbered footnote reference.
""",
"""\
<document>
    <paragraph>
        <footnote_reference auto="1">
         is the first auto-numbered footnote reference.
        <footnote_reference auto="1">
         is the second auto-numbered footnote reference.
    <footnote auto="1">
        <paragraph>
            Auto-numbered footnote 1.
    <footnote auto="1">
        <paragraph>
            Auto-numbered footnote 2.
    <footnote auto="1">
        <paragraph>
            Auto-numbered footnote 3.
    <paragraph>
        <footnote_reference auto="1">
         is the third auto-numbered footnote reference.
"""],
["""\
[#third]_ is a reference to the third auto-numbered footnote.

.. [#first] First auto-numbered footnote.
.. [#second] Second auto-numbered footnote.
.. [#third] Third auto-numbered footnote.

[#second]_ is a reference to the second auto-numbered footnote.
[#first]_ is a reference to the first auto-numbered footnote.
[#third]_ is another reference to the third auto-numbered footnote.

Here are some internal cross-references to the targets generated by
the footnotes: first_, second_, third_.
""",
"""\
<document>
    <paragraph>
        <footnote_reference auto="1" refname="third">
         is a reference to the third auto-numbered footnote.
    <footnote auto="1" id="id1" name="first">
        <paragraph>
            First auto-numbered footnote.
    <footnote auto="1" id="id2" name="second">
        <paragraph>
            Second auto-numbered footnote.
    <footnote auto="1" id="id3" name="third">
        <paragraph>
            Third auto-numbered footnote.
    <paragraph>
        <footnote_reference auto="1" refname="second">
         is a reference to the second auto-numbered footnote.
        <footnote_reference auto="1" refname="first">
         is a reference to the first auto-numbered footnote.
        <footnote_reference auto="1" refname="third">
         is another reference to the third auto-numbered footnote.
    <paragraph>
        Here are some internal cross-references to the targets generated by
        the footnotes: \n\
        <reference refname="first">
            first
        , \n\
        <reference refname="second">
            second
        , \n\
        <reference refname="third">
            third
        .
"""],
["""\
Mixed anonymous and labelled auto-numbered footnotes:

[#four]_ should be 4, [#]_ should be 1,
[#]_ should be 3, [#]_ is one too many,
[#two]_ should be 2, and [#six]_ doesn't exist.

.. [#] Auto-numbered footnote 1.
.. [#two] Auto-numbered footnote 2.
.. [#] Auto-numbered footnote 3.
.. [#four] Auto-numbered footnote 4.
.. [#five] Auto-numbered footnote 5.
.. [#five] Auto-numbered footnote 5 again (duplicate).
""",
"""\
<document>
    <paragraph>
        Mixed anonymous and labelled auto-numbered footnotes:
    <paragraph>
        <footnote_reference auto="1" refname="four">
         should be 4, \n\
        <footnote_reference auto="1">
         should be 1,
        <footnote_reference auto="1">
         should be 3, \n\
        <footnote_reference auto="1">
         is one too many,
        <footnote_reference auto="1" refname="two">
         should be 2, and \n\
        <footnote_reference auto="1" refname="six">
         doesn't exist.
    <footnote auto="1">
        <paragraph>
            Auto-numbered footnote 1.
    <footnote auto="1" id="id1" name="two">
        <paragraph>
            Auto-numbered footnote 2.
    <footnote auto="1">
        <paragraph>
            Auto-numbered footnote 3.
    <footnote auto="1" id="id2" name="four">
        <paragraph>
            Auto-numbered footnote 4.
    <footnote auto="1" dupname="five" id="id3">
        <paragraph>
            Auto-numbered footnote 5.
    <footnote auto="1" dupname="five" id="id4">
        <system_message level="2" type="WARNING">
            <paragraph>
                Duplicate explicit target name: "five"
        <paragraph>
            Auto-numbered footnote 5 again (duplicate).
"""],
]

if __name__ == '__main__':
    import unittest
    unittest.main(defaultTest='suite')
